name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change if using a different branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t santoshpremi/bg-remover-01:latest .
          docker push santoshpremi/bg-remover-01:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Connect to AWS EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull santoshpremi/bg-remover-01:latest
            docker stop stoic_pare || true
            docker rm stoic_pare || true
            docker run -d --name stoic_pare -p 80:80 santoshpremi/bg-remover-01:latest
